[[language]]
name = "swift"
auto-format = true
formatter = { command = "swift-format", args = ["format", "--configuration", ".swift-format"] }
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "python"
auto-format = false

[language-server.pylsp.config.pylsp]
plugins.pyls_mypy.enabled = true
plugins.pyls_mypy.live_mode = true
plugins.flake8.maxLineLength = 300
plugins.flake8.ignore = ["E302", "E305"]
plugins.pycodestyle.maxLineLength = 300
plugins.pycodestyle.ignore = ["E302", "E305"]

[[language]]
name = "svelte"
auto-format = true
formatter = { command = "prettier", args = ["--plugin", "prettier-plugin-svelte", "--parser", "svelte"] }

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "javascript"
auto-format = false
formatter = { command = "prettier", args = ["--parser", "babel"] }

[[language]]
name = "css"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "css"] }

[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "^typ(st)?$"
file-types = ["typ"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
roots = []
language-servers = [ "typst-lsp" ]

[[grammar]]
name = "typst"
source = { git = "https://github.com/uben0/tree-sitter-typst", rev = "e35aa22395fdde82bbc4b5700c324ce346dfc9e5" }

[[language]]
name = "dafny"
scope = "source.dafny"
file-types = ["dfy"]
language-servers = [ "dafny-ls" ]
grammar = "rust"

[language-server.dafny-ls]
command = "dafny"
args = [ "server" ]

[[language]]
name = "cpp"
file-types = ["cpp", "metal"]

[[language]]
name = "c"
file-types = ["c", "h"]
indent = { tab-width = 8, unit = "        " }
language-servers = [ "sourcekit-lsp" ]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'$' = '$'

[language-server.rust-analyzer.config]
checkOnSave.command = "clippy"

[language-server.typst-lsp]
command = "typst-lsp"
